"""Tests for custom template path and label overrides."""

from __future__ import annotations

from datetime import datetime

from src.models import Episode, TranscriptResult
from src.writer.markdown import DEFAULT_LABELS, MarkdownGenerator


def _make_episode(**overrides):
    defaults = {
        "guid": "test-guid",
        "title": "Test Episode",
        "podcast_name": "Test Podcast",
        "pub_date": datetime(2025, 1, 15, 10, 0, 0),
        "audio_url": "https://example.com/audio.mp3",
        "duration": "01:00:00",
        "show_notes": "Show notes content",
        "link": "https://example.com/ep",
        "tags": ["tech"],
    }
    defaults.update(overrides)
    return Episode(**defaults)


def _make_transcript(**overrides):
    defaults = {
        "text": "Full transcript text",
        "paragraphs": ["Paragraph one", "Paragraph two"],
        "summary": "AI summary text",
        "chapters": [{"title": "Chapter 1", "summary": "First chapter"}],
        "keywords": ["AI", "podcast"],
    }
    defaults.update(overrides)
    return TranscriptResult(**defaults)


class TestDefaultLabels:
    def test_default_labels_exist(self):
        assert "ai_summary" in DEFAULT_LABELS
        assert "chapters" in DEFAULT_LABELS
        assert "show_notes" in DEFAULT_LABELS
        assert "transcript" in DEFAULT_LABELS

    def test_default_template_renders_chinese_labels(self):
        gen = MarkdownGenerator("templates")
        result = gen.render(_make_episode(), _make_transcript())
        assert "## AI 摘要" in result
        assert "## 章节速览" in result
        assert "## Show Notes" in result
        assert "## 全文转写" in result


class TestCustomLabels:
    def test_english_labels(self):
        labels = {
            "ai_summary": "AI Summary",
            "chapters": "Chapters",
            "show_notes": "Show Notes",
            "transcript": "Full Transcript",
            "podcast": "Podcast",
            "date": "Date",
            "duration": "Duration",
            "link": "Link",
            "link_text": "Episode",
        }
        gen = MarkdownGenerator("templates", labels=labels)
        result = gen.render(_make_episode(), _make_transcript())
        assert "## AI Summary" in result
        assert "## Chapters" in result
        assert "## Full Transcript" in result
        assert "**Podcast**" in result
        assert "[Episode]" in result

    def test_partial_label_override(self):
        """Override only some labels, rest use defaults."""
        gen = MarkdownGenerator("templates", labels={"ai_summary": "Summary"})
        result = gen.render(_make_episode(), _make_transcript())
        assert "## Summary" in result
        assert "## 章节速览" in result  # default preserved
        assert "## 全文转写" in result  # default preserved

    def test_custom_footer(self):
        gen = MarkdownGenerator(
            "templates",
            labels={"footer": "Generated by FM2note v{version}"},
        )
        result = gen.render(_make_episode(), _make_transcript())
        assert "Generated by FM2note v" in result


class TestCustomTemplatePath:
    def test_custom_template_dir(self, tmp_path):
        """Load template from a custom directory."""
        custom_template = tmp_path / "custom.md.j2"
        custom_template.write_text(
            "# {{ episode.title }}\nASR: {{ asr_engine }}\n"
            "{{ labels.ai_summary | default('Summary') }}\n"
        )
        gen = MarkdownGenerator(
            template_dir=str(tmp_path),
            template_name="custom.md.j2",
        )
        result = gen.render(_make_episode(), _make_transcript(), asr_engine="funasr")
        assert "# Test Episode" in result
        assert "ASR: funasr" in result

    def test_custom_template_with_labels(self, tmp_path):
        """Custom template uses labels dict."""
        custom_template = tmp_path / "note.md.j2"
        custom_template.write_text(
            "## {{ labels.transcript }}\n{% for p in transcript.paragraphs %}\n"
            "{{ p }}\n{% endfor %}\n"
        )
        gen = MarkdownGenerator(
            template_dir=str(tmp_path),
            template_name="note.md.j2",
            labels={"transcript": "Transcript"},
        )
        result = gen.render(_make_episode(), _make_transcript())
        assert "## Transcript" in result
        assert "Paragraph one" in result


class TestMarkdownGeneratorConstructor:
    def test_default_constructor(self):
        gen = MarkdownGenerator()
        assert gen._template_name == "podcast_note.md.j2"
        assert gen._labels == DEFAULT_LABELS

    def test_constructor_with_all_params(self, tmp_path):
        (tmp_path / "t.md.j2").write_text("{{ episode.title }}")
        gen = MarkdownGenerator(
            template_dir=str(tmp_path),
            template_name="t.md.j2",
            labels={"ai_summary": "S"},
        )
        assert gen._template_name == "t.md.j2"
        assert gen._labels["ai_summary"] == "S"
        # Other labels should still have defaults
        assert gen._labels["chapters"] == DEFAULT_LABELS["chapters"]
